// RTK Query API for Tasks
// RTK Query is Redux Toolkit's data fetching solution
// Think of it as a smart way to fetch data from your API and cache it automatically

import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import type { Task } from "@/lib/db/schema";

// Define the base API
// This creates an API "slice" that handles all task-related API calls
export const tasksApi = createApi({
  // Unique identifier for this API slice
  reducerPath: "tasksApi",
  
  // Base URL for all API calls
  // In Next.js, API routes are at /api/tasks
  baseQuery: fetchBaseQuery({
    baseUrl: "/api/tasks",
    // Include credentials (cookies) in requests
    credentials: "include",
    // Prepare headers (we'll add auth token here later)
    prepareHeaders: (headers) => {
      // Get token from localStorage (if using client-side storage)
      if (typeof window !== "undefined") {
        const token = localStorage.getItem("token");
        if (token) {
          headers.set("authorization", `Bearer ${token}`);
        }
      }
      return headers;
    },
  }),
  
  // Tag types for cache invalidation
  // When we create/update/delete a task, we invalidate the cache
  tagTypes: ["Task"],
  
  // Define API endpoints
  endpoints: (builder) => ({
    // GET /api/tasks - Fetch all tasks
    // This automatically creates a hook: useGetTasksQuery()
    getTasks: builder.query<
      { tasks: Task[]; total: number },
      {
        status?: "pending" | "in_progress" | "completed";
        priority?: "low" | "medium" | "high";
        search?: string;
        category?: string;
      }
    >({
      query: (params) => {
        // Build query string from parameters
        const searchParams = new URLSearchParams();
        if (params.status) searchParams.append("status", params.status);
        if (params.priority) searchParams.append("priority", params.priority);
        if (params.search) searchParams.append("search", params.search);
        if (params.category) searchParams.append("category", params.category);
        
        const queryString = searchParams.toString();
        return {
          url: queryString ? `?${queryString}` : "",
          method: "GET",
        };
      },
      // Tag this query so we can invalidate it later
      providesTags: ["Task"],
    }),
    
    // GET /api/tasks/:id - Fetch single task
    // Creates hook: useGetTaskQuery(id)
    getTask: builder.query<Task, number>({
      query: (id) => `/${id}`,
      providesTags: (result, error, id) => [{ type: "Task", id }],
    }),
    
    // POST /api/tasks - Create new task
    // Creates hook: useCreateTaskMutation()
    createTask: builder.mutation<
      { task: Task },
      {
        title: string;
        description?: string;
        dueDate?: string;
        priority?: "low" | "medium" | "high";
        status?: "pending" | "in_progress" | "completed";
        category?: string;
      }
    >({
      query: (body) => ({
        url: "",
        method: "POST",
        body,
      }),
      // Invalidate tasks list after creating
      invalidatesTags: ["Task"],
    }),
    
    // PUT /api/tasks/:id - Update task
    // Creates hook: useUpdateTaskMutation()
    updateTask: builder.mutation<
      { task: Task },
      {
        id: number;
        data: {
          title?: string;
          description?: string;
          dueDate?: string;
          priority?: "low" | "medium" | "high";
          status?: "pending" | "in_progress" | "completed";
          category?: string;
        };
      }
    >({
      query: ({ id, data }) => ({
        url: `/${id}`,
        method: "PUT",
        body: data,
      }),
      invalidatesTags: (result, error, { id }) => [
        { type: "Task", id },
        "Task",
      ],
    }),
    
    // DELETE /api/tasks/:id - Delete task
    // Creates hook: useDeleteTaskMutation()
    deleteTask: builder.mutation<{ message: string }, number>({
      query: (id) => ({
        url: `/${id}`,
        method: "DELETE",
      }),
      invalidatesTags: ["Task"],
    }),
  }),
});

// Export hooks for use in components
// These are automatically generated by RTK Query
export const {
  useGetTasksQuery,
  useGetTaskQuery,
  useCreateTaskMutation,
  useUpdateTaskMutation,
  useDeleteTaskMutation,
} = tasksApi;

